### PR TITLE
Nested versions of tidyr functions

### PR DESCRIPTION
**Pull request by joranE**
I know we weren't sure whether these belonged in a separate package or not, but I went ahead and just made them since it was pretty easy. No worries if you don't end up thinking they belong.

### CODE REVIEW

**Comment by markjrieke** [comment]
ooh - this is great! It may take me a bit to run through & check, but from mulling it over I generally agree that there's a lot of crossover functionality between dplyr/tidyr.

**Comment by markjrieke** [comment]
Hey @joranE - I haven't gone through in detail, but can you please run `devtools::check()`/`devtools::document()` locally & address any issues that crop up. For example, noticing off-hand that the DESCRIPTION file will need updating. Thanks!

**Comment by markjrieke** [comment]
Also tagging #13 in this PR

**Comment by joranE** [comment]
Sure, updated with:

- Fixed test for `nest_extract()` which I'd bungled badly somehow
- Committed doc changes after running `devtools::document()`
- Updated DESCRIPTION to move **tidyr** to Depends

`devtools::test()` reports all tests passing and `devtools::check()` returns only a single warning about needing **qpdf** to check on size reduction of PDFs. Not sure how to address that; I installed **qpdf** with homebrew (and the R package) but the warning is still appearing.

**Comment by markjrieke** [comment]
Hey @joranE ! Just wanted to touch base --- it's been a bit hectic on my end but I hopefully should have a chance to review/merge this weekend.

**Comment by markjrieke** [comment]
Hey @joranE --- thanks for your patience here! I'm mostly done running through checks & whatnot & can merge today. This is a pretty significant set of additions --- can I list you as a contributor on the pkgdown site?

**Comment by joranE** [comment]
Awesome, thanks! That's funny, it's a fair bit of code (and functionality) being added, but it didn't feel all that significant; mostly just copy & pasting the mutate+map pattern from the existing code. But yes, it's fine to include me as a contributor, thanks!

**Comment by markjrieke** [comment]
awesome! thank you for your work on this --- I've [added you as a contributor](https://github.com/markjrieke/nplyr/blob/main/DESCRIPTION) as well

**Pull request merged**
